
# Define services
services:

  mysql:
    image: mysql:5.7
    restart: always
    # Create a volume named marketplace-data and store them in Docker virtual hard drive (typically /var/lib/docker/volumes)
    volumes:
      - marketplace-data:/var/lib/mysql
    env_file:
      - ./project/.env.dev
      
  django-mysql:
    build: 
      context: project
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    # Create a volume in the working directory to update when code changes
    volumes:
      - ./project:/project
    env_file:
      - ./project/.env.dev
    depends_on:
      - mysql


  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    # Enable hot reloading for react to update frontend with code changes
    environment:
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true
    depends_on:
      - django-mysql
      
# Create a volume for the database to be stored 
volumes:
  marketplace-data: